markstory/sphinxcontrib-phpdomain

CHANGES
setup.py
sphinxcontrib/phpdomain.py

This PR allows us to run docs under sphinx 1.4.5. This is a BC for people using an old version of sphinx.
We probably need to add tags to avoid BC changes, I don't know how it works for sphinx packages.

Sphinx 1.4.5

---

sphinxcontrib/phpdomain.py
test/index.rst
test/test_nesting_regression.rst

When `php:function` is used to annotate methods the build should not fail. However it will generate incorrect output as function should be used for global functions and not methods.
Refs #2

Don't fatally error on function nodes that include classnames.

---

sphinxcontrib/phpdomain.py

Code is fixed with reference to python domain coding.
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/javascript.py#L84
Problem happen in case below:
```
.. php:method:: inputs(array $fields = [], $options = [])
```
In this case, result should be:
```
Cake\View\Helper\FormHelper::inputs(array $fields = [], $options = []])
```
But actually wrong:
```
Cake\View\Helper\FormHelper::inputs(array $fields = , []$options = []])
```
Above problem already fixed by this PR.
----
Unfortunately, this code still has another comma defect. The defect emerges when in case below:
```
.. php:method:: foo(string $var =",", string $buz = true)
```
In this case, separating with comma, arguments become 3 of 'string $var="', '"', 'string $buz = true'.
However, last defect is a problem of …

Fix problem that [] and , in argument list are swapped

---

setup.py

This approach has several benefits:
- closes the opened file explicitly
- doesn't use an OS-dependent file separator to find `requirements.txt`
- doesn't make assumptions about curdir during the installation process via pip (which worked as-is under a Py2 environment, but choked under a Py3 environment)

add contextual open around requirements.txt read in setup.py

---

MANIFEST.in

In order to include requirements.txt in the source distribution, and thus make it available to `setup.py` for pip installs, it appears you must have it listed in `MANIFEST.in`. This should (I hope) finish addressing issue #10.

add requirements.txt to MANIFEST

---

sphinxcontrib/phpdomain.py

With this the :any: referencing can be used in restructuredText, so that you don't need to specify the type.

Implement resolve_any_xref to support :any: referencing

---

sphinxcontrib/phpdomain.py
test/test_doc.rst

This PR adds support for visibility definitions and modifiers like static/final/abstract.
Those will be added as annotation to the rendering and must be omitted when referencing the class,method or property.

Allow visibility modifiers

---

sphinxcontrib/phpdomain.py

Use builtin python domain as pattern for parallel read safety:
- revise clear_doc() to be in line with python domain's clear_doc()
- add merge_domain() built in the same mode as python domain's merge_domain()

Prepare for parallel read safety

---

sphinxcontrib/phpdomain.py

To avoid this error:
```
File "/usr/local/lib/python3.7/site-packages/sphinxcontrib/phpdomain.py", line 284, in add_target_and_index
self.env.warn(
AttributeError: 'BuildEnvironment' object has no attribute 'warn'
```
Solution from javascript domain:
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/javascript.py#L112

Update for Sphinx 2.0.1

---

sphinxcontrib/phpdomain.py
test/test_doc.rst
test/test_doc2.rst

Add a new directive that allows namespaces to be re-used and enables `namespace` to be the canonical reference. This re-uses patterns used in the ruby and python domains and gives a solution to #27

Add currentmodule directive

---

.github/workflows/ci.yml

2.7 is end of life, and dropping python 2 can be part of the next release.

Stop testing with old python

---

sphinxcontrib/phpdomain.py

Change the process_link regexp to actually hide all the parts before class/method name. Please see unit tests carried out on regex101: https://regex101.com/r/eNUo8C/1

process_link regexp change

---

.gitignore
doc/reference.rst
sphinxcontrib/phpdomain.py
test/test_doc.rst

This PR adds support for [PHP enumerations](https://www.php.net/enum).
In general, the `:php:enum:` and `:php:case:` directives work just like `:php:class:` and `:php:const:`, respectively. However, to support [backed enums](https://www.php.net/manual/en/language.enumerations.backed.php), I got a little creative and introduced a minor new syntax to the signature line.
Here's a very simple, basic enum example:
```
.. php:enum:: Suit
.. php:case:: Hearts
.. php:case:: Diamonds
.. php:case:: Clubs
.. php:case:: Spades
```
Here's the same example as a backed enum:
```
.. php:enum:: Suit : string
.. php:case:: Hearts : 'H'
.. php:case:: Diamonds : 'D'
.. php:case:: Clubs : 'C'
.. php:case:: Spades : 'S'
```
This new syntax is effectively the same as this:
```
.. php:enum:: Suit() -> string
.. …
```

Support PHP enumerations

---

.github/workflows/doc.yml
doc/index.rst

- Fix include directive error message:
doc/index.rst:1: CRITICAL: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '../README'.
This error may have appeared when upgrading the maximum Sphinx version.
- Add GitHub action workflow to build & publish doc
You will need to follow the steps (1) to (4) from [this GitHub doc](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow), then once merged the doc should be accessible at this URL: https://markstory.github.io/sphinxcontrib-phpdomain/
Fixes #45

Add GitHub action workflow to build & publish doc

---

sphinxcontrib/phpdomain.py

This allows to automatically add entries for domain objects in contents table with Sphinx >= 5.2.
See <https://github.com/sphinx-doc/sphinx/pull/10807> and <https://github.com/sphinx-doc/sphinx/pull/10886>
See also an example here with my (still small) documentation : https://status.club1.fr/sphinx-inventory-parser/index.html
(I didn't add the `php:namespace` in my docs as it caused issues with `:php:attr:` references for some reason, I will open an issue (and/or a PR) for this bug soon)
_Same results as `toc_object_entries_show_parents = domain`_
_the default theme does not support it very well :sweat_smile:_

Add contents entries for object & :nocontentsentry:

---

.github/workflows/ci.yml
sphinxcontrib/phpdomain.py
test/test_doc.rst

Pull in the changes made my @n-peugnet and also fix prefix removal
on namespaced class links as they were wrong too.
Fixes #44

Fix prefix-less link generation for properties and classes

---

README.rst
doc/reference.rst

- Fix indentation in "Quick Sample".
- Add :nocontentsentry: option to "Quick Sample" example to prevent polluting the table of contents.
- Use real rst cross-references with :rst:dir: role.

Cleanup doc (nocontentsentry, indentation, rst xrefs)

---

README.rst
doc/changes.rst
doc/index.rst
doc/usage.rst

- Move Quick Sample into its own usage.rst page of the doc, as it is only correctly rendered in a Sphinx documentation.
- Move Changelog inclusion into its own page of the doc, as its growing size took a lot of space in the home page.
These two changes leave a lot more room for the table of contents, as it was quite buried in the home page before.
Fixes #41

Reorganise documentation & usage example

---

README.rst
sphinxcontrib/phpdomain.py

This option allows to disable the creation of index entries for targeted objects. See <https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#basic-markup>
Inspired from [this change](https://github.com/sphinx-doc/sphinx/pull/10807/commits/3a4778f158a765e0c6745075778d6c971b390c7b#diff-4440aa368513769284c3d18efa39fc65c05f3f7ed3deeabbc2f2def311ae7e2b).

Support noindexentry option for domain objects

---

sphinxcontrib/phpdomain.py

Resolves TypeError: can only concatenate str (not "_StrPath") to str in sphinxcontrib/phpdomain.py:396 by explicitly converting fullname to string before string formatting.
The add_target_and_index method was failing when fullname parameter was a _StrPath object instead of a string. Added str() conversion to ensure proper string concatenation in the error message.

[fix]: TypeError in phpdomain when fullname is _StrPath object
